# youtuber = ""

# print(f"Subscribe to {youtuber}")

noun1 = input("Please enter a noun: ")
verb1 = input("Please enter a verb: ")
noun2 = input("Please enter another noun: ")
noun3 = input("Please enter the third noun: ")
noun4 = input("Please enter the fourth noun: ")
noun5 = input("Please enter another noun: ")
verb2 = input("Please enter another verb: ")
adj1 = input("Please enter an adjective: ")
verb3 = input("Please enter any verb: ")
adj2 = input("Please enter the second adjective: ")
noun6 = input("Please enter any noun number six: ")
pronoun1 = input("Please enter a pronoun: ")
noun7 = input("Please enter any noun: ")
verb4 = input("Please enter verb number four: ")
adj3 = input("Please enter any adjective: ")
pronoun2 = input("Please enter any pronoun: ")
pronoun3 = input("Please enter another pronoun: ")
verb5 = input("Please enter another verb: ")
pronoun4 = input("Please enter the fourth pronoun: ")
noun8 = input("Please enter another noun: ")
adj4 = input("Please enter your least final adjective: ")
pronoun5 = input("Please enter a pronoun: ")
noun9 = input("Please enter a noun, number nine: ")
noun10 = input("We are almost there, please enter another noun: ")
pronoun6 = input("Please enter any pronoun: ")
noun11 = input("Please enter another noun: ")
noun12 = input("Please enter another noun: ")
pronoun7 = input("Please enter another pronoun: ")
verb6 = input("Please enter another verb: ")
verb7 = input("Please continue entering another verb: ")
noun13 = input("Please enter a noun number thirteen: ")
pronoun8 = input("Please enter the eight pronoun: ")
verb8 = input("Please enter another verb: ")
verb9 = input("Please enter another verb: ")
demonstrative_pronoun = input("Please enter a demonstrative pronoun: ")
noun14 = input("Please enter another noun: ")
noun15 = input("Please enter another noun: ")
pronoun9 = input("Please enter any pronoun: ")
verb10 = input("Please enter another verb number ten: ")
pronoun10 = input("Please enter a pronoun: ")
noun16 = input("I like your effort, please enter another noun: ")
verb11 = input("Please enter another verb: ")
noun17 = input("Please enter another noun: ")
noun18 = input("Please enter any noun: ")
verb12 = input("Please enter any verb number twelve: ")
noun19 = input("Almost there, please enter another noun: ")
verb13 = input("Please enter any verb: ")
noun20 = input("Please enter another noun: ")
pronoun11 = input("Please enter any pronoun: ")
verb14 = input("Please enter another verb: ")
pronoun12 = input("Please enter the second last Pronoun: ")
verb15 = input("Please enter the second last verb: ")
pronoun13 = input("Please enter the last Pronoun: ")
verb16 = input("Please enter the last verb: ")
noun21 = input("Please enter the second last noun: ")
noun22 = input("Hurray! Please enter the last noun:) : ")
adj5 = input("Please enter the last adjective: ")
author = input("Please enter an author: ")
book = input("Please enter a book: ")
year = input("Please enter any year: ")

madlib = f"Read the {noun1} below and then {verb1} the questions that follow. In {noun2}, we meet and learn from three different kinds of {noun3}. The first and probably the most {noun4} is that which we might {verb2} the Discipline of Nature or of Reality. This type of discipline requires that when people {verb3} to do the {adj1} things, they will get the wrong results. If, for instance, a musician {verb4} the wrong key, he or she hears the {adj2} note. If the nail is not squarely hit on the head, it bends and it therefore has to be pulled out. {noun6} meet the Discipline of Nature every time {pronoun1} try to do something. This is why it is so important in school to give {noun7} more chances to do things, instead of just {verb5} or listening to someone talk. This discipline is a {adj3} teacher. The learner never has to wait long for the answer, {pronoun2} usually comes quickly, often instantly. {pronoun3} answer is often clear, and it points towards the needed correction. This way, the learner does not only {verb6} that what was done is wrong, but also why, and what {pronoun4} need to do instead. Finally, and most importantly, the giver of the {noun8}, call her Nature is impersonal, impartial and {adj4}. {pronoun5} does not give {noun9} or make judgment. With {noun10}, one always gets an opportunity to start afresh, this time with the intention of doing things right.{pronoun6} next type of {noun11} is the Discipline of Culture. Man is a social and cultural {noun12}. Everyone, thus, senses around {pronoun7} this discipline, this network of agreements, customs, habits and rules {verb7} the society together. People always seek to {verb8} the {noun13} and be part of it. {pronoun8} {verb9} very carefully what other people around them are doing and wish to {verb10} the same. {demonstrative_pronoun} unwritten rules regarding how to act in specific situations are called social norms.  Social norms help delineate what is acceptable {noun14}. For example, it is not acceptable to he loud and boisterous in a place of {noun15}. {pronoun9}e third discipline is the one most people {verb11} to when they speak of discipline — the Discipline of Superior Force. It is the discipline of “{pronoun10} do what I tell you or I’ll make you wish you had.” There is bound to be some of this in a person’s {noun16}. Living as we do surrounded by things that can {verb12} us and our {noun17}, we cannot avoid the Discipline of Superior Force.  For example, no one can let a {noun18} find out from experience the danger of {verb13} with fire.  So along with other precautions, the {noun19} is told not to play with fire or {pronoun11} will be punished. There are situations where all the three disciplines {verb14}. We often hear people say that {noun20} will never do anything unless they are compelled to.  But in their private lives, or in co- curricular activities in school, {pronoun12} often {verb15} themselves, willingly and wholeheartedly to very intense disciplines simply because {pronoun13} want to {verb16} to do a given thing well.  So, discipline, does not only stem from authority figures such as {noun21} and {noun22} but it also comes from a person’s {adj5} to do right. Adapted from {author} {book}, {year}"

print(madlib)
